name: birthday_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.10
  yandex_mapkit: ^3.3.0
  flutter_screenutil: ^5.7.0
  freezed: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  path_provider: ^2.0.15
  auto_route: ^7.7.1
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.6.2
  auto_route_generator: ^7.2.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
        - asset: assets/fonts/jost/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/jost/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jost/Jost-Bold.ttf
          weight: 700
    - family: Yeseva One
      fonts:
        - asset: assets/fonts/yeseva_one/YesevaOne-Regular.ttf

